### ISSUE TITLE
does checker.sh work on ubuntu?

### ISSUE THREAD

**Issue by rafmeeusen** [phretor/intel-leak-checker#1]
I did a simple test: 
$ cat pubkeys/keys.rsa | xxd -r -ps > binfile
$ ./checker.sh binfile

with result:
No keys found: you may not be affected

I would expect this to get a hit? Or not?

**Comment by phretor** [comment]
```bash
$ cat pubkeys/keys.rsa | head -1 | xxd -r -ps > binfile
$ ./checker.sh binfile

Keys found: you're likely affected.
```

Reason I think is that `-r` will also convert `\n` into binary, which I'm not sure how my dirty `grep` will handle :-)

**Comment by rafmeeusen** [comment]
Still no hit for me if I literally copy your example. 
I think related to the xxd in checker.sh making columns in ascii output on my machine; 
(ubuntu 22.04, xxd version string: "xxd 2021-10-22 by Juergen Weigert et al.") 
manpage not explaining what -c 0 is doing, but I guess purpose is to have no newlines? 
now guessing you're having another xxd version? 
anyway, thanks for quick feedback!

**Comment by phretor** [comment]
It's actually a valid point. I tested it on macOS only and GNU vs. BSD versions of the same CLI utilities are known to have small (but annoying) discrepancies. I added a warning in the README. If you have time to debug and find a non-macOS specific way to do the same test, feel free to send a PR!

**Comment by rafmeeusen** [comment]
Did a quick fix for myself by editing checker.sh as follows (added tr -d) : 
xxd -g 0 -c 0 -ps "$1" | tr -d '\n' | grep -qioE -f pubkeys/keys.rsa && \

Maybe not the cleanest, but I think it should never harm since xxd output should not contain any '\n' .

**Comment by AkechiShiro** [comment]
@phretor Could you please precise your `xxd` version ?
@rafmeeusen could you please precise yours as well.

I did the below test under ArchLinux, and it says that I'm likely affected, this may be just a version related issue ? Or maybe, xxd on ArchLinux behaves closer to the one on macOS for some reason, but that's surprising.
> I did a simple test: 
> $ cat pubkeys/keys.rsa | xxd -r -ps > binfile 
> $ ./checker.sh binfile

Results : `Keys found: you're likely affected.`

Output of `xxd --version` :  `xxd 2022-01-14 by Juergen Weigert et al.`

**Comment by rafmeeusen** [comment]
Weird. 
Already mentioned my xxd version in earlier comment.

**Comment by rafmeeusen** [comment]
@AkechiShiro 
Seems indeed introduced between my version and your version, if I read this well: https://unix.stackexchange.com/questions/218514/xxd-output-without-line-breaks

**Comment by AkechiShiro** [comment]
Sorry, I didn't see you already mentioned your version at the beginning of this issue, you're right according to this comment : https://unix.stackexchange.com/a/706374/287583

It looks like that, this issue/weird behavior is fixed since (`-c 0` or `-p 0` can be used) : 
> version `xxd` version 2022-01-14 (coming with [vim 8.2.4088](https://github.com/vim/vim/commit/c0a1d370fa655cea9eaa74f5e605b95825dc9de1)) or newer

@phretor I'll open up a quick PR to update the README with this information, could help others folks, I'm sure.

**Comment by phretor** [comment]
Thank you @AkechiShiro

**Comment by phretor** [comment]
I think https://github.com/phretor/intel-leak-checker/commit/792a6a79061a617dc39706a476944a11e0e9e8bc resolves this.
